services:
  # backend:
  #   image: Plants # Remember to change the image name
  #   build:
  #     context: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - database
  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - path: .env
